//
//  UIColor+Extension.swift
//  Studybuddy
//
//  Created by yue on 12/1/23.
//

import UIKit

extension UIColor {
    
    // DO NOT EDIT THIS FILE
    
    static let hc = HC()
    
    struct HC {
        let black = UIColor.black
        let rose = UIColor(red: 1, green: 0.53, blue: 0.53, alpha: 1)
        let lightYellow = UIColor(red: 0.99, green: 0.96, blue: 0.77, alpha: 1)
        let lightGrey = UIColor(red: 0.85, green: 0.85, blue: 0.85, alpha: 1)
        let textGrey = UIColor(red: 0.69, green: 0.67, blue: 0.67, alpha: 1)
        let white = UIColor.white
    }

}
